### ISSUE TITLE
Could not connect: `invalid option: window-size`

### ISSUE THREAD

**Issue by pvonmoradi** [lhotari/action-upterm#12]
Any ideas?
```
Run lhotari/action-upterm@v1
upterm

Auto-generating ~/.ssh/known_hosts by attempting connection to uptermd.upterm.dev
Pseudo-terminal will not be allocated because stdin is not a terminal.

Warning: Permanently added 'uptermd.upterm.dev' (ED25519) to the list of known hosts.

Connection closed by xxx.yyy.zzz.aa port 22

Adding actor "pvonmoradi" to allowed users.
Fetching SSH keys registered with GitHub profiles: pvonmoradi
Fetched 1 ssh public keys
Creating a new session. Connecting to upterm server ssh://uptermd.upterm.dev:22
invalid option: window-size

invalid option: window-size

Error: 1
```

Here is the relavant parts from my yml file:

```yaml
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which
          #triggered the workflow
          limit-access-to-actor: true
            ## limits ssh access and adds the ssh public keys of the listed
            #GitHub users
          limit-access-to-users: pvonmoradi
```
